const PLANT_IMAGES: Record<string, any> = {
  baobab:             require('@/assets/images/plants/baobab.png'),
  fromager:           require('@/assets/images/plants/fromager.png'),
  'caïlcédrat':       require('@/assets/images/plants/cailcedrat.png'),
  ficus:              require('@/assets/images/plants/ficus.png'),
  tamarinier:         require('@/assets/images/plants/tamarinier.png'),
  iroko:              require('@/assets/images/plants/iroko.png'),
  moringa:            require('@/assets/images/plants/moringa.png'),
  neem:               require('@/assets/images/plants/neem.png'),
  papayer:            require('@/assets/images/plants/papayer.png'),
  gingembre:          require('@/assets/images/plants/gingembre.png'),
  bissap:             require('@/assets/images/plants/bissap.png'),
  kinkeliba:          require('@/assets/images/plants/kinkeliba.png'),
  kalanchoe:          require('@/assets/images/plants/kalanchoe.png'),
  artemisia:          require('@/assets/images/plants/artemisia.png'),
  kolatier:           require('@/assets/images/plants/kolatier.png'),
  nere:               require('@/assets/images/plants/nere.png'),
  karite:             require('@/assets/images/plants/karite.png'),
  gombo:              require('@/assets/images/plants/gombo.png'),
  igname:             require('@/assets/images/plants/igname.png'),
  manioc:             require('@/assets/images/plants/manioc.png'),
  arachide:           require('@/assets/images/plants/arachide.png'),
  sesame:             require('@/assets/images/plants/sesame.png'),
  vetiver:            require('@/assets/images/plants/vetiver.png'),
  acacia:             require('@/assets/images/plants/acacia.png'),
  citronnelle:        require('@/assets/images/plants/citronnelle.png'),
  raphia:             require('@/assets/images/plants/raphia.png'),
  'basilic-africain': require('@/assets/images/plants/basilic-africain.png'),
  mil:                require('@/assets/images/plants/mil.png'),
  sorgho:             require('@/assets/images/plants/sorgho.png'),
  fonio:              require('@/assets/images/plants/fonio.png'),
  ronier:             require('@/assets/images/plants/ronier.png'),
  dattier:            require('@/assets/images/plants/dattier.png'),
  'palmier-huile':    require('@/assets/images/plants/palmier-huile.png'),
  cocotier:           require('@/assets/images/plants/cocotier.png'),
};

export default PLANT_IMAGES;
